#if DEBUG
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Nag.Api.OpenApi;

/// <summary>
/// Mirrors the XML <c>&lt;summary&gt;</c>-derived operation summary into the
/// operation description when description is empty or carries Wolverine's
/// autogenerated <c>VERB_path_segments</c> slug (e.g. <c>POST_devices</c>).
///
/// Why both fields: Swagger UI renders <c>summary</c> as the operation header
/// and <c>description</c> as the longer prose underneath. <c>openapi-zod-client</c>
/// only reads <c>description</c> when generating JSDoc on the typed alias,
/// so without this filter the prose stays trapped in the spec and the
/// mobile API client's IntelliSense shows the slug instead of the real
/// rationale. Copying summary → description gives both consumers something
/// useful with one set of <c>///</c> blocks in the C# source.
/// </summary>
public sealed class XmlSummaryAsDescriptionFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (string.IsNullOrWhiteSpace(operation.Summary))
            return;

        // Unconditional copy: Wolverine populates `Description` from the
        // method name's path-derived slug (e.g. `GET_sync`,
        // `POST_accounts_me_devices`), which is junk for both Swagger UI's
        // detail pane and openapi-zod-client's JSDoc. The XML
        // `///&nbsp;<summary>` block on the C# method is the source of
        // truth; copy it over whatever Wolverine wrote.
        operation.Description = operation.Summary;
    }
}
#endif
