services:
  postgres:
    image: postgres:17.7-alpine # NOTE keep matching the Neon Postgres major version
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql

volumes:
  my-db: {}
