#if DEBUG
using Microsoft.OpenApi;
using Nag.Api.OpenApi;

namespace Nag.Api.Configuration;

public static class SwaggerExtensions
{
    public static IServiceCollection AddNagSwagger(this IServiceCollection services)
    {
        services.AddEndpointsApiExplorer();
        services.AddSwaggerGen(c =>
        {
            c.UseAllOfToExtendReferenceSchemas();
            c.SchemaFilter<EnumSchemaFilter>();
            c.DocumentFilter<CommandSchemasFilter>();
            c.DocumentFilter<OrphanIResultSchemaFilter>();
            c.OperationFilter<AllowAnonymousSecurityFilter>();
            c.OperationFilter<UndeclaredResponseFilter>();

            // Pull `/// <summary>` blocks from both assemblies' XML doc
            // files into OpenAPI `summary` fields. Each csproj has
            // `<GenerateDocumentationFile>true</GenerateDocumentationFile>`,
            // so Nag.Api.xml + Nag.Core.xml land next to the DLLs in the
            // build output. Existence-checked because the Nag.Core.xml
            // build might race the spec generation in CI.
            foreach (var xml in new[] { "Nag.Api.xml", "Nag.Core.xml" })
            {
                var path = Path.Combine(AppContext.BaseDirectory, xml);
                if (File.Exists(path))
                    c.IncludeXmlComments(path, includeControllerXmlComments: true);
            }

            // Must come *after* IncludeXmlComments — that helper registers
            // its own XmlCommentsOperationFilter, which is what actually
            // populates operation.Summary from the C# XML doc blocks.
            // Filters run in registration order, so registering this one
            // earlier would see Wolverine's `GET_sync`-style autogenerated
            // summary and dutifully mirror that junk into description.
            c.OperationFilter<XmlSummaryAsDescriptionFilter>();
            c.AddSecurityDefinition(
                "Bearer",
                new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.Http,
                    Scheme = "bearer",
                    BearerFormat = "Token",
                    In = ParameterLocation.Header,
                    Name = "Authorization",
                    Description =
                        "Either a per-device HMAC token (issued at POST /devices, "
                        + "POST /accounts/me/devices, or POST /accounts/me/identity) "
                        + "or a Clerk JWT.",
                }
            );
            c.AddSecurityRequirement(doc => new OpenApiSecurityRequirement
            {
                { new OpenApiSecuritySchemeReference("Bearer", doc), new List<string>() },
            });
        });
        return services;
    }
}
#endif
